name: Build-Slide

on:
  # push/pull時に実行
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # 手動実行も可
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # "build" ジョブ
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # tikzでdspスタイルを使っているので落としてくる
      - name: Download tikz-dsp style file
        run: |
          curl -OL http://www.texample.net/media/tikz/examples/zip/tikz-dsp.zip
          unzip tikz-dsp.zip
        
      # スライドビルド
      - name: Build Slide
        uses: xu-cheng/latex-action@v2
        env:
          TEXINPUTS: ".:./tikz-dsp//:"
        with:
          working_directory: ./slide
          root_file: introduction_to_wavelet.tex
          args: -pdfdvi -latex=platex
