name: Build-Slide

on:
  # push/pull時に実行
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # 手動実行も可
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # "build" ジョブ
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      # スライドビルド
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ./slide/introduction_to_wavelet.tex
          args: -pdfdvi -latex=platex -synctex=1 -e "$dvipdf='dvipdfmx %O %S';$bibtex='bibtex';$makeindex='mendex';"
