name: Build Slide

on:
  # 定期実行
  schedule:
    - cron: '0 0 * * *'
  # push/pull時に実行
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 手動実行も可
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 追加のスタイルファイルの導入
      - name: Download extra style file
        uses: wei/wget@v1.1.1
        with:
          args: http://www.texample.net/media/tikz/examples/zip/tikz-dsp.zip https://github.com/h-kitagawa/plistings/archive/master.zip

      # パッケージの展開
      - name: Unzip downloaded package
        run: |
          unzip tikz-dsp.zip -d slide/tikz-dsp
          unzip master.zip -d slide
          
      # スライドビルド
      - name: Build Slide
        uses: xu-cheng/latex-action@v2
        env:
          TEXINPUTS: ".:./tikz-dsp/library/tex/latex/tikz-dsp//:./plistings-master/:"
        with:
          working_directory: ./slide
          root_file: introduction_to_wavelet.tex
          args: -pdfdvi -latex=platex

      # 成果物のアップロード
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./slide/introduction_to_wavelet.pdf
