name: Python CI

on:
  # push/pull時に実行
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # 手動実行も可
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 準備
      - name: Install dependencies
        run: |
          pip install pylint numpy scipy

      # Pylint
      - name: Pylint
        run: |
          cd implementation
          pylint fwt.py

      # Python unit test
      - name: Unit Test
        run: |
          cd implementation
          python test_fwt.py
